spring:
  application:
    name: SpaceCatsMarket
  datasource:
    url: jdbc:postgresql://localhost:5432/space_cats_market_db
    username: postgres
    password: password
  liquibase:
    change-log: classpath:database/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
